/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockPriceOracleInterface extends Interface {
    getFunction(nameOrSignature: "PRICE_DECIMALS" | "getTokenPrice" | "oracleID" | "setOracleID" | "setPrice"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CustomOracleSet" | "OracleSet"): EventFragment;

    encodeFunctionData(functionFragment: 'PRICE_DECIMALS', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTokenPrice', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'oracleID', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setOracleID', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'setPrice', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'PRICE_DECIMALS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracleID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOracleID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPrice', data: BytesLike): Result;
  }

  
    export namespace CustomOracleSetEvent {
      export type InputTuple = [token: AddressLike, oracle: AddressLike];
      export type OutputTuple = [token: string, oracle: string];
      export interface OutputObject {token: string, oracle: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OracleSetEvent {
      export type InputTuple = [token: AddressLike, oracleID: BytesLike];
      export type OutputTuple = [token: string, oracleID: string];
      export interface OutputObject {token: string, oracleID: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MockPriceOracle extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockPriceOracle;
    waitForDeployment(): Promise<this>;

    interface: MockPriceOracleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    PRICE_DECIMALS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getTokenPrice: TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    oracleID: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    setOracleID: TypedContractMethod<
      [arg0: AddressLike, arg1: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setPrice: TypedContractMethod<
      [token: AddressLike, priceUSD: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'PRICE_DECIMALS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenPrice'): TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'oracleID'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setOracleID'): TypedContractMethod<
      [arg0: AddressLike, arg1: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPrice'): TypedContractMethod<
      [token: AddressLike, priceUSD: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CustomOracleSet'): TypedContractEvent<CustomOracleSetEvent.InputTuple, CustomOracleSetEvent.OutputTuple, CustomOracleSetEvent.OutputObject>;
getEvent(key: 'OracleSet'): TypedContractEvent<OracleSetEvent.InputTuple, OracleSetEvent.OutputTuple, OracleSetEvent.OutputObject>;

    filters: {
      
      'CustomOracleSet(address,address)': TypedContractEvent<CustomOracleSetEvent.InputTuple, CustomOracleSetEvent.OutputTuple, CustomOracleSetEvent.OutputObject>;
      CustomOracleSet: TypedContractEvent<CustomOracleSetEvent.InputTuple, CustomOracleSetEvent.OutputTuple, CustomOracleSetEvent.OutputObject>;
    

      'OracleSet(address,bytes32)': TypedContractEvent<OracleSetEvent.InputTuple, OracleSetEvent.OutputTuple, OracleSetEvent.OutputObject>;
      OracleSet: TypedContractEvent<OracleSetEvent.InputTuple, OracleSetEvent.OutputTuple, OracleSetEvent.OutputObject>;
    
    };
  }