/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IAction, IActionInterface } from "../../interfaces/IAction.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "params",
        "type": "bytes"
      },
      {
        "internalType": "bytes[]",
        "name": "ctx",
        "type": "bytes[]"
      }
    ],
    "name": "execute",
    "outputs": [
      {
        "internalType": "uint32[]",
        "name": "updatedSlots",
        "type": "uint32[]"
      },
      {
        "internalType": "bytes[]",
        "name": "updatedValues",
        "type": "bytes[]"
      },
      {
        "internalType": "address",
        "name": "volumeToken",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "volumeAmount",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IAction__factory {
    static readonly abi = _abi;
    static createInterface(): IActionInterface {
      return new Interface(_abi) as IActionInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IAction {
      return new Contract(address, _abi, runner) as unknown as IAction;
    }
  }
  