/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FeeDepositAction } from './FeeDepositAction.js';
export type { IVaultMinDeposit } from './IVaultMinDeposit.js';