/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IVaultMinDeposit, IVaultMinDepositInterface } from "../../../../examples/actions/FeeDepositAction.sol/IVaultMinDeposit.js";

  const _abi = [
  {
    "inputs": [],
    "name": "minFeeDeposit",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IVaultMinDeposit__factory {
    static readonly abi = _abi;
    static createInterface(): IVaultMinDepositInterface {
      return new Interface(_abi) as IVaultMinDepositInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IVaultMinDeposit {
      return new Contract(address, _abi, runner) as unknown as IVaultMinDeposit;
    }
  }
  