/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace StrategyBuilderVault {
      
    export type StepStruct = {stepType: BigNumberish, target: AddressLike, selector: BytesLike, nextOnTrue: BigNumberish, nextOnFalse: BigNumberish, data: BytesLike}

    export type StepStructOutput = [stepType: bigint, target: string, selector: string, nextOnTrue: bigint, nextOnFalse: bigint, data: string] & {stepType: bigint, target: string, selector: string, nextOnTrue: bigint, nextOnFalse: bigint, data: string }
  
    }

  export interface StrategyBuilderVaultInterface extends Interface {
    getFunction(nameOrSignature: "DONE" | "MAX_STEPS" | "automationCount" | "createAutomation" | "createOwnerAutomation" | "creator" | "decodeContextDiff" | "depositFees" | "depositToken" | "executeAutomation" | "feeChainEid" | "feeRegistry" | "getAutomation" | "getContext" | "initialize" | "isTriggerMet" | "minFeeDeposit" | "owner" | "priceOracle" | "renounceOwnership" | "setAutomationActive" | "setContext" | "setContextSlot" | "setMinFeeDeposit" | "transferOwnership" | "updateAutomationSteps" | "withdrawETH"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AutomationActiveChanged" | "AutomationCreated" | "AutomationExecuted" | "AutomationStepsUpdated" | "ContextSlotSet" | "FeeAccrued" | "FeesSettled" | "Initialized" | "MinFeeDepositUpdated" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'DONE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_STEPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'automationCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'createAutomation', values: [StrategyBuilderVault.StepStruct[]]): string;
encodeFunctionData(functionFragment: 'createOwnerAutomation', values: [StrategyBuilderVault.StepStruct[]]): string;
encodeFunctionData(functionFragment: 'creator', values?: undefined): string;
encodeFunctionData(functionFragment: 'decodeContextDiff', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'depositFees', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'depositToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeAutomation', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'feeChainEid', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAutomation', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getContext', values?: undefined): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'isTriggerMet', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'minFeeDeposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'priceOracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAutomationActive', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'setContext', values: [BytesLike[]]): string;
encodeFunctionData(functionFragment: 'setContextSlot', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setMinFeeDeposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateAutomationSteps', values: [BigNumberish, StrategyBuilderVault.StepStruct[]]): string;
encodeFunctionData(functionFragment: 'withdrawETH', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'DONE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_STEPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'automationCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createAutomation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createOwnerAutomation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decodeContextDiff', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeAutomation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeChainEid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAutomation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getContext', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isTriggerMet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minFeeDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'priceOracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAutomationActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setContext', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setContextSlot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMinFeeDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateAutomationSteps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawETH', data: BytesLike): Result;
  }

  
    export namespace AutomationActiveChangedEvent {
      export type InputTuple = [automationId: BigNumberish, active: boolean];
      export type OutputTuple = [automationId: bigint, active: boolean];
      export interface OutputObject {automationId: bigint, active: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AutomationCreatedEvent {
      export type InputTuple = [automationId: BigNumberish, stepCount: BigNumberish];
      export type OutputTuple = [automationId: bigint, stepCount: bigint];
      export interface OutputObject {automationId: bigint, stepCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AutomationExecutedEvent {
      export type InputTuple = [automationId: BigNumberish, executor: AddressLike];
      export type OutputTuple = [automationId: bigint, executor: string];
      export interface OutputObject {automationId: bigint, executor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AutomationStepsUpdatedEvent {
      export type InputTuple = [automationId: BigNumberish, stepCount: BigNumberish];
      export type OutputTuple = [automationId: bigint, stepCount: bigint];
      export interface OutputObject {automationId: bigint, stepCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ContextSlotSetEvent {
      export type InputTuple = [slot: BigNumberish];
      export type OutputTuple = [slot: bigint];
      export interface OutputObject {slot: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeAccruedEvent {
      export type InputTuple = [automationId: BigNumberish, stepIndex: BigNumberish, target: AddressLike, selector: BytesLike, volumeUSD: BigNumberish, feeUSD: BigNumberish];
      export type OutputTuple = [automationId: bigint, stepIndex: bigint, target: string, selector: string, volumeUSD: bigint, feeUSD: bigint];
      export interface OutputObject {automationId: bigint, stepIndex: bigint, target: string, selector: string, volumeUSD: bigint, feeUSD: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeesSettledEvent {
      export type InputTuple = [automationId: BigNumberish, executor: AddressLike, depositToken: AddressLike, creator: AddressLike, totalFeeUSD: BigNumberish, depositTokenAmount: BigNumberish, gasCompTokens: BigNumberish];
      export type OutputTuple = [automationId: bigint, executor: string, depositToken: string, creator: string, totalFeeUSD: bigint, depositTokenAmount: bigint, gasCompTokens: bigint];
      export interface OutputObject {automationId: bigint, executor: string, depositToken: string, creator: string, totalFeeUSD: bigint, depositTokenAmount: bigint, gasCompTokens: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MinFeeDepositUpdatedEvent {
      export type InputTuple = [newMinFeeDeposit: BigNumberish];
      export type OutputTuple = [newMinFeeDeposit: bigint];
      export interface OutputObject {newMinFeeDeposit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface StrategyBuilderVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): StrategyBuilderVault;
    waitForDeployment(): Promise<this>;

    interface: StrategyBuilderVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DONE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_STEPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    automationCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    createAutomation: TypedContractMethod<
      [steps: StrategyBuilderVault.StepStruct[], ],
      [bigint],
      'nonpayable'
    >
    

    
    createOwnerAutomation: TypedContractMethod<
      [steps: StrategyBuilderVault.StepStruct[], ],
      [bigint],
      'nonpayable'
    >
    

    
    creator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    decodeContextDiff: TypedContractMethod<
      [data: BytesLike, ],
      [[bigint[], string[]] & {slots: bigint[], values: string[] }],
      'view'
    >
    

    
    depositFees: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    depositToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    executeAutomation: TypedContractMethod<
      [automationId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    feeChainEid: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    feeRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAutomation: TypedContractMethod<
      [automationId: BigNumberish, ],
      [[boolean, boolean, StrategyBuilderVault.StepStructOutput[]] & {active: boolean, ownerOnly: boolean, steps: StrategyBuilderVault.StepStructOutput[] }],
      'view'
    >
    

    
    getContext: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [initialOwner: AddressLike, feeRegistry_: AddressLike, depositToken_: AddressLike, creator_: AddressLike, priceOracle_: AddressLike, feeChainEid_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    isTriggerMet: TypedContractMethod<
      [automationId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    minFeeDeposit: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    priceOracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setAutomationActive: TypedContractMethod<
      [automationId: BigNumberish, active: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setContext: TypedContractMethod<
      [ctx: BytesLike[], ],
      [void],
      'nonpayable'
    >
    

    
    setContextSlot: TypedContractMethod<
      [slot: BigNumberish, value: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setMinFeeDeposit: TypedContractMethod<
      [minAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateAutomationSteps: TypedContractMethod<
      [automationId: BigNumberish, steps: StrategyBuilderVault.StepStruct[], ],
      [void],
      'nonpayable'
    >
    

    
    withdrawETH: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DONE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_STEPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'automationCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createAutomation'): TypedContractMethod<
      [steps: StrategyBuilderVault.StepStruct[], ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createOwnerAutomation'): TypedContractMethod<
      [steps: StrategyBuilderVault.StepStruct[], ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'creator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'decodeContextDiff'): TypedContractMethod<
      [data: BytesLike, ],
      [[bigint[], string[]] & {slots: bigint[], values: string[] }],
      'view'
    >;
getFunction(nameOrSignature: 'depositFees'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'executeAutomation'): TypedContractMethod<
      [automationId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'feeChainEid'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'feeRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAutomation'): TypedContractMethod<
      [automationId: BigNumberish, ],
      [[boolean, boolean, StrategyBuilderVault.StepStructOutput[]] & {active: boolean, ownerOnly: boolean, steps: StrategyBuilderVault.StepStructOutput[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getContext'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [initialOwner: AddressLike, feeRegistry_: AddressLike, depositToken_: AddressLike, creator_: AddressLike, priceOracle_: AddressLike, feeChainEid_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isTriggerMet'): TypedContractMethod<
      [automationId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'minFeeDeposit'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'priceOracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAutomationActive'): TypedContractMethod<
      [automationId: BigNumberish, active: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setContext'): TypedContractMethod<
      [ctx: BytesLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setContextSlot'): TypedContractMethod<
      [slot: BigNumberish, value: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMinFeeDeposit'): TypedContractMethod<
      [minAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateAutomationSteps'): TypedContractMethod<
      [automationId: BigNumberish, steps: StrategyBuilderVault.StepStruct[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawETH'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AutomationActiveChanged'): TypedContractEvent<AutomationActiveChangedEvent.InputTuple, AutomationActiveChangedEvent.OutputTuple, AutomationActiveChangedEvent.OutputObject>;
getEvent(key: 'AutomationCreated'): TypedContractEvent<AutomationCreatedEvent.InputTuple, AutomationCreatedEvent.OutputTuple, AutomationCreatedEvent.OutputObject>;
getEvent(key: 'AutomationExecuted'): TypedContractEvent<AutomationExecutedEvent.InputTuple, AutomationExecutedEvent.OutputTuple, AutomationExecutedEvent.OutputObject>;
getEvent(key: 'AutomationStepsUpdated'): TypedContractEvent<AutomationStepsUpdatedEvent.InputTuple, AutomationStepsUpdatedEvent.OutputTuple, AutomationStepsUpdatedEvent.OutputObject>;
getEvent(key: 'ContextSlotSet'): TypedContractEvent<ContextSlotSetEvent.InputTuple, ContextSlotSetEvent.OutputTuple, ContextSlotSetEvent.OutputObject>;
getEvent(key: 'FeeAccrued'): TypedContractEvent<FeeAccruedEvent.InputTuple, FeeAccruedEvent.OutputTuple, FeeAccruedEvent.OutputObject>;
getEvent(key: 'FeesSettled'): TypedContractEvent<FeesSettledEvent.InputTuple, FeesSettledEvent.OutputTuple, FeesSettledEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'MinFeeDepositUpdated'): TypedContractEvent<MinFeeDepositUpdatedEvent.InputTuple, MinFeeDepositUpdatedEvent.OutputTuple, MinFeeDepositUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'AutomationActiveChanged(uint32,bool)': TypedContractEvent<AutomationActiveChangedEvent.InputTuple, AutomationActiveChangedEvent.OutputTuple, AutomationActiveChangedEvent.OutputObject>;
      AutomationActiveChanged: TypedContractEvent<AutomationActiveChangedEvent.InputTuple, AutomationActiveChangedEvent.OutputTuple, AutomationActiveChangedEvent.OutputObject>;
    

      'AutomationCreated(uint32,uint256)': TypedContractEvent<AutomationCreatedEvent.InputTuple, AutomationCreatedEvent.OutputTuple, AutomationCreatedEvent.OutputObject>;
      AutomationCreated: TypedContractEvent<AutomationCreatedEvent.InputTuple, AutomationCreatedEvent.OutputTuple, AutomationCreatedEvent.OutputObject>;
    

      'AutomationExecuted(uint32,address)': TypedContractEvent<AutomationExecutedEvent.InputTuple, AutomationExecutedEvent.OutputTuple, AutomationExecutedEvent.OutputObject>;
      AutomationExecuted: TypedContractEvent<AutomationExecutedEvent.InputTuple, AutomationExecutedEvent.OutputTuple, AutomationExecutedEvent.OutputObject>;
    

      'AutomationStepsUpdated(uint32,uint256)': TypedContractEvent<AutomationStepsUpdatedEvent.InputTuple, AutomationStepsUpdatedEvent.OutputTuple, AutomationStepsUpdatedEvent.OutputObject>;
      AutomationStepsUpdated: TypedContractEvent<AutomationStepsUpdatedEvent.InputTuple, AutomationStepsUpdatedEvent.OutputTuple, AutomationStepsUpdatedEvent.OutputObject>;
    

      'ContextSlotSet(uint32)': TypedContractEvent<ContextSlotSetEvent.InputTuple, ContextSlotSetEvent.OutputTuple, ContextSlotSetEvent.OutputObject>;
      ContextSlotSet: TypedContractEvent<ContextSlotSetEvent.InputTuple, ContextSlotSetEvent.OutputTuple, ContextSlotSetEvent.OutputObject>;
    

      'FeeAccrued(uint32,uint32,address,bytes4,uint256,uint256)': TypedContractEvent<FeeAccruedEvent.InputTuple, FeeAccruedEvent.OutputTuple, FeeAccruedEvent.OutputObject>;
      FeeAccrued: TypedContractEvent<FeeAccruedEvent.InputTuple, FeeAccruedEvent.OutputTuple, FeeAccruedEvent.OutputObject>;
    

      'FeesSettled(uint32,address,address,address,uint256,uint256,uint256)': TypedContractEvent<FeesSettledEvent.InputTuple, FeesSettledEvent.OutputTuple, FeesSettledEvent.OutputObject>;
      FeesSettled: TypedContractEvent<FeesSettledEvent.InputTuple, FeesSettledEvent.OutputTuple, FeesSettledEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'MinFeeDepositUpdated(uint256)': TypedContractEvent<MinFeeDepositUpdatedEvent.InputTuple, MinFeeDepositUpdatedEvent.OutputTuple, MinFeeDepositUpdatedEvent.OutputObject>;
      MinFeeDepositUpdated: TypedContractEvent<MinFeeDepositUpdatedEvent.InputTuple, MinFeeDepositUpdatedEvent.OutputTuple, MinFeeDepositUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }