/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockRevertingAction, MockRevertingActionInterface } from "../../test/MockRevertingAction.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "code",
        "type": "uint256"
      }
    ],
    "name": "MockActionReason",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "params",
        "type": "bytes"
      },
      {
        "internalType": "bytes[]",
        "name": "",
        "type": "bytes[]"
      }
    ],
    "name": "execute",
    "outputs": [
      {
        "internalType": "uint32[]",
        "name": "",
        "type": "uint32[]"
      },
      {
        "internalType": "bytes[]",
        "name": "",
        "type": "bytes[]"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234601c57600e6020565b61032e61002b823961032e90f35b6026565b60405190565b5f80fdfe60806040526004361015610013575b610246565b61001d5f3561002c565b6324856bc30361000e57610228565b60e01c90565b5f80fd5b5f80fd5b5f80fd5b5f80fd5b5f80fd5b5f80fd5b909182601f830112156100845781359167ffffffffffffffff831161007f57602001926001830284011161007a57565b610046565b610042565b61003e565b909182601f830112156100c35781359167ffffffffffffffff83116100be5760200192602083028401116100b957565b610046565b610042565b61003e565b9091604082840312610122575f82013567ffffffffffffffff811161011d57836100f391840161004a565b929093602082013567ffffffffffffffff8111610118576101149201610089565b9091565b61003a565b61003a565b610036565b63ffffffff1690565b61013990610127565b9052565b9061014a81602093610130565b0190565b60200190565b8181106101615750505090565b90919261017a610174600192865161013d565b9461014e565b9101919091610154565b5190565b60209181520190565b90825f9392825e0152565b601f801991011690565b6101c56101ce6020936101d3936101bc81610184565b93848093610188565b95869101610191565b61019c565b0190565b906101e1916101a6565b90565b60200190565b8383106101f957505050505090565b9091929394602061021b610215838560019503875289516101d7565b976101e4565b93019301919392906101ea565b34610241576102383660046100c8565b929190916102ba565b610032565b5f80fd5b606090565b606090565b90565b61026081610254565b0361026757565b5f80fd5b9050359061027882610257565b565b9060208282031261029357610290915f0161026b565b90565b610036565b6102a190610254565b9052565b91906102b8905f60208501940190610298565b565b6102f4916102dd916102ca61024a565b506102d361024f565b509081019061027a565b5f91829163b8aa2b2760e01b8352600483016102a5565b0390fdfea26469706673582212207f4ac1383a08a90a6b300689bcc8a26b1a9c1476635079836ccdf8faf10ea73c64736f6c634300081c0033";

  
      type MockRevertingActionConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockRevertingActionConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockRevertingAction__factory extends ContractFactory {
    
      constructor(...args: MockRevertingActionConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockRevertingAction & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockRevertingAction__factory {
      return super.connect(runner) as MockRevertingAction__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockRevertingActionInterface {
      return new Interface(_abi) as MockRevertingActionInterface;
    }
    
    override attach(address: string | Addressable): MockRevertingAction {
      return super.attach(address) as MockRevertingAction;
    }
  static connect(address: string, runner?: ContractRunner | null): MockRevertingAction {
      return new Contract(address, _abi, runner) as unknown as MockRevertingAction;
    }
  }

  
  