/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IntervalConditionInterface extends Interface {
    getFunction(nameOrSignature: "afterExecution" | "check"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'afterExecution', values: [BytesLike, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'check', values: [BytesLike, BytesLike[]]): string;

    decodeFunctionResult(functionFragment: 'afterExecution', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'check', data: BytesLike): Result;
  }

  

  export interface IntervalCondition extends BaseContract {
    
    connect(runner?: ContractRunner | null): IntervalCondition;
    waitForDeployment(): Promise<this>;

    interface: IntervalConditionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    afterExecution: TypedContractMethod<
      [params: BytesLike, ctx: BytesLike[], ],
      [[bigint[], string[]] & {updatedSlots: bigint[], updatedValues: string[] }],
      'view'
    >
    

    
    check: TypedContractMethod<
      [params: BytesLike, ctx: BytesLike[], ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'afterExecution'): TypedContractMethod<
      [params: BytesLike, ctx: BytesLike[], ],
      [[bigint[], string[]] & {updatedSlots: bigint[], updatedValues: string[] }],
      'view'
    >;
getFunction(nameOrSignature: 'check'): TypedContractMethod<
      [params: BytesLike, ctx: BytesLike[], ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }