/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as feeDepositActionSol from './FeeDepositAction.sol/index.js';
export type { feeDepositActionSol };
export type { ERC20TransferAction } from './ERC20TransferAction.js';