/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ActionLibHarnessInterface extends Interface {
    getFunction(nameOrSignature: "NO_SLOT" | "fullBalance" | "readUint256Slot" | "singleSlotDiff"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'NO_SLOT', values?: undefined): string;
encodeFunctionData(functionFragment: 'fullBalance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'readUint256Slot', values: [BytesLike[], BigNumberish]): string;
encodeFunctionData(functionFragment: 'singleSlotDiff', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'NO_SLOT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fullBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'readUint256Slot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'singleSlotDiff', data: BytesLike): Result;
  }

  

  export interface ActionLibHarness extends BaseContract {
    
    connect(runner?: ContractRunner | null): ActionLibHarness;
    waitForDeployment(): Promise<this>;

    interface: ActionLibHarnessInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    NO_SLOT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    fullBalance: TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    readUint256Slot: TypedContractMethod<
      [ctx: BytesLike[], slot: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    singleSlotDiff: TypedContractMethod<
      [slot: BigNumberish, value: BigNumberish, ],
      [[bigint[], string[]] & {slots: bigint[], values: string[] }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'NO_SLOT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'fullBalance'): TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'readUint256Slot'): TypedContractMethod<
      [ctx: BytesLike[], slot: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'singleSlotDiff'): TypedContractMethod<
      [slot: BigNumberish, value: BigNumberish, ],
      [[bigint[], string[]] & {slots: bigint[], values: string[] }],
      'view'
    >;

    

    filters: {
      
    };
  }