/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ICuratedRegistryInterface extends Interface {
    getFunction(nameOrSignature: "addCuratedTarget" | "curator" | "isCurated" | "removeCuratedTarget" | "setCurator"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CuratorChanged" | "TargetCurationChanged"): EventFragment;

    encodeFunctionData(functionFragment: 'addCuratedTarget', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'curator', values?: undefined): string;
encodeFunctionData(functionFragment: 'isCurated', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'removeCuratedTarget', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setCurator', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'addCuratedTarget', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'curator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isCurated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeCuratedTarget', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCurator', data: BytesLike): Result;
  }

  
    export namespace CuratorChangedEvent {
      export type InputTuple = [previousCurator: AddressLike, newCurator: AddressLike];
      export type OutputTuple = [previousCurator: string, newCurator: string];
      export interface OutputObject {previousCurator: string, newCurator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TargetCurationChangedEvent {
      export type InputTuple = [target: AddressLike, kind: BigNumberish, curator: AddressLike, curated: boolean];
      export type OutputTuple = [target: string, kind: bigint, curator: string, curated: boolean];
      export interface OutputObject {target: string, kind: bigint, curator: string, curated: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ICuratedRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): ICuratedRegistry;
    waitForDeployment(): Promise<this>;

    interface: ICuratedRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addCuratedTarget: TypedContractMethod<
      [target: AddressLike, kind: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    curator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isCurated: TypedContractMethod<
      [target: AddressLike, kind: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    removeCuratedTarget: TypedContractMethod<
      [target: AddressLike, kind: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setCurator: TypedContractMethod<
      [newCurator: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addCuratedTarget'): TypedContractMethod<
      [target: AddressLike, kind: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'curator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isCurated'): TypedContractMethod<
      [target: AddressLike, kind: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'removeCuratedTarget'): TypedContractMethod<
      [target: AddressLike, kind: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCurator'): TypedContractMethod<
      [newCurator: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CuratorChanged'): TypedContractEvent<CuratorChangedEvent.InputTuple, CuratorChangedEvent.OutputTuple, CuratorChangedEvent.OutputObject>;
getEvent(key: 'TargetCurationChanged'): TypedContractEvent<TargetCurationChangedEvent.InputTuple, TargetCurationChangedEvent.OutputTuple, TargetCurationChangedEvent.OutputObject>;

    filters: {
      
      'CuratorChanged(address,address)': TypedContractEvent<CuratorChangedEvent.InputTuple, CuratorChangedEvent.OutputTuple, CuratorChangedEvent.OutputObject>;
      CuratorChanged: TypedContractEvent<CuratorChangedEvent.InputTuple, CuratorChangedEvent.OutputTuple, CuratorChangedEvent.OutputObject>;
    

      'TargetCurationChanged(address,uint8,address,bool)': TypedContractEvent<TargetCurationChangedEvent.InputTuple, TargetCurationChangedEvent.OutputTuple, TargetCurationChangedEvent.OutputObject>;
      TargetCurationChanged: TypedContractEvent<TargetCurationChangedEvent.InputTuple, TargetCurationChangedEvent.OutputTuple, TargetCurationChangedEvent.OutputObject>;
    
    };
  }