/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface ERC20TransferActionInterface extends Interface {
    getFunction(nameOrSignature: "execute"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'execute', values: [BytesLike, BytesLike[]]): string;

    decodeFunctionResult(functionFragment: 'execute', data: BytesLike): Result;
  }

  

  export interface ERC20TransferAction extends BaseContract {
    
    connect(runner?: ContractRunner | null): ERC20TransferAction;
    waitForDeployment(): Promise<this>;

    interface: ERC20TransferActionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    execute: TypedContractMethod<
      [params: BytesLike, ctx: BytesLike[], ],
      [[bigint[], string[], string, bigint] & {updatedSlots: bigint[], updatedValues: string[], volumeToken: string, volumeAmount: bigint }],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'execute'): TypedContractMethod<
      [params: BytesLike, ctx: BytesLike[], ],
      [[bigint[], string[], string, bigint] & {updatedSlots: bigint[], updatedValues: string[], volumeToken: string, volumeAmount: bigint }],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }