/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace IAaveV3Pool {
      
    export type ReserveConfigurationMapStruct = {data: BigNumberish}

    export type ReserveConfigurationMapStructOutput = [data: bigint] & {data: bigint }
  

    export type ReserveDataStruct = {configuration: IAaveV3Pool.ReserveConfigurationMapStruct, liquidityIndex: BigNumberish, currentLiquidityRate: BigNumberish, variableBorrowIndex: BigNumberish, currentVariableBorrowRate: BigNumberish, currentStableBorrowRate: BigNumberish, lastUpdateTimestamp: BigNumberish, id: BigNumberish, aTokenAddress: AddressLike, stableDebtTokenAddress: AddressLike, variableDebtTokenAddress: AddressLike, interestRateStrategyAddress: AddressLike, accruedToTreasury: BigNumberish, unbacked: BigNumberish, isolationModeTotalDebt: BigNumberish}

    export type ReserveDataStructOutput = [configuration: IAaveV3Pool.ReserveConfigurationMapStructOutput, liquidityIndex: bigint, currentLiquidityRate: bigint, variableBorrowIndex: bigint, currentVariableBorrowRate: bigint, currentStableBorrowRate: bigint, lastUpdateTimestamp: bigint, id: bigint, aTokenAddress: string, stableDebtTokenAddress: string, variableDebtTokenAddress: string, interestRateStrategyAddress: string, accruedToTreasury: bigint, unbacked: bigint, isolationModeTotalDebt: bigint] & {configuration: IAaveV3Pool.ReserveConfigurationMapStructOutput, liquidityIndex: bigint, currentLiquidityRate: bigint, variableBorrowIndex: bigint, currentVariableBorrowRate: bigint, currentStableBorrowRate: bigint, lastUpdateTimestamp: bigint, id: bigint, aTokenAddress: string, stableDebtTokenAddress: string, variableDebtTokenAddress: string, interestRateStrategyAddress: string, accruedToTreasury: bigint, unbacked: bigint, isolationModeTotalDebt: bigint }
  
    }

  export interface MockAaveV3PoolInterface extends Interface {
    getFunction(nameOrSignature: "aTokenOf" | "borrow" | "debtOf" | "debtTokenOf" | "getReserveData" | "getUserAccountData" | "repay" | "seedDebt" | "setAToken" | "setDebtToken" | "supply" | "withdraw"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'aTokenOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'borrow', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'debtOf', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'debtTokenOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getReserveData', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserAccountData', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'repay', values: [AddressLike, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'seedDebt', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setAToken', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setDebtToken', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supply', values: [AddressLike, BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [AddressLike, BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'aTokenOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'borrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'debtOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'debtTokenOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReserveData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserAccountData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'seedDebt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDebtToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  

  export interface MockAaveV3Pool extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockAaveV3Pool;
    waitForDeployment(): Promise<this>;

    interface: MockAaveV3PoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    aTokenOf: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    borrow: TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, arg2: BigNumberish, arg3: BigNumberish, onBehalfOf: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    debtOf: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    debtTokenOf: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    getReserveData: TypedContractMethod<
      [asset: AddressLike, ],
      [IAaveV3Pool.ReserveDataStructOutput],
      'view'
    >
    

    
    getUserAccountData: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint]],
      'view'
    >
    

    
    repay: TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, arg2: BigNumberish, onBehalfOf: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    seedDebt: TypedContractMethod<
      [asset: AddressLike, user: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setAToken: TypedContractMethod<
      [asset: AddressLike, aToken: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setDebtToken: TypedContractMethod<
      [asset: AddressLike, debtToken: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supply: TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, onBehalfOf: AddressLike, arg3: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, to: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'aTokenOf'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'borrow'): TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, arg2: BigNumberish, arg3: BigNumberish, onBehalfOf: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'debtOf'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'debtTokenOf'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getReserveData'): TypedContractMethod<
      [asset: AddressLike, ],
      [IAaveV3Pool.ReserveDataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getUserAccountData'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'repay'): TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, arg2: BigNumberish, onBehalfOf: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'seedDebt'): TypedContractMethod<
      [asset: AddressLike, user: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAToken'): TypedContractMethod<
      [asset: AddressLike, aToken: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDebtToken'): TypedContractMethod<
      [asset: AddressLike, debtToken: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supply'): TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, onBehalfOf: AddressLike, arg3: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, to: AddressLike, ],
      [bigint],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }