/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface MockPoolAddressesProviderInterface extends Interface {
    getFunction(nameOrSignature: "getPool" | "getPriceOracle" | "oracleAddr" | "poolAddr"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getPool', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPriceOracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'oracleAddr', values?: undefined): string;
encodeFunctionData(functionFragment: 'poolAddr', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'getPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPriceOracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracleAddr', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'poolAddr', data: BytesLike): Result;
  }

  

  export interface MockPoolAddressesProvider extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockPoolAddressesProvider;
    waitForDeployment(): Promise<this>;

    interface: MockPoolAddressesProviderInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getPool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getPriceOracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    oracleAddr: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    poolAddr: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getPool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getPriceOracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'oracleAddr'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'poolAddr'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }