/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ICuratedRegistry, ICuratedRegistryInterface } from "../../interfaces/ICuratedRegistry.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "caller",
        "type": "address"
      }
    ],
    "name": "NotCurator",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "enum ICuratedRegistry.TargetKind",
        "name": "kind",
        "type": "uint8"
      }
    ],
    "name": "TargetAlreadyCurated",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      }
    ],
    "name": "TargetNotAContract",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "enum ICuratedRegistry.TargetKind",
        "name": "kind",
        "type": "uint8"
      }
    ],
    "name": "TargetNotCurated",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroAddress",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "previousCurator",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "newCurator",
        "type": "address"
      }
    ],
    "name": "CuratorChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "enum ICuratedRegistry.TargetKind",
        "name": "kind",
        "type": "uint8"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "curator",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "curated",
        "type": "bool"
      }
    ],
    "name": "TargetCurationChanged",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "enum ICuratedRegistry.TargetKind",
        "name": "kind",
        "type": "uint8"
      }
    ],
    "name": "addCuratedTarget",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "curator",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "enum ICuratedRegistry.TargetKind",
        "name": "kind",
        "type": "uint8"
      }
    ],
    "name": "isCurated",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "enum ICuratedRegistry.TargetKind",
        "name": "kind",
        "type": "uint8"
      }
    ],
    "name": "removeCuratedTarget",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "newCurator",
        "type": "address"
      }
    ],
    "name": "setCurator",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ICuratedRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): ICuratedRegistryInterface {
      return new Interface(_abi) as ICuratedRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ICuratedRegistry {
      return new Contract(address, _abi, runner) as unknown as ICuratedRegistry;
    }
  }
  